### ISSUE TITLE
Creación de directorio `doc` y reubicación de `memoria.pdf`

### ISSUE THREAD

**Issue by lauramcastro** [adrilpz/vyv#1]
Como documentación, el fichero `memoria.pdf` debería ubicarse en el directorio específico correspondiente (`doc`).

**Comment by lauramcastro** [comment]
Asimismo, cuando cerréis una _issue_ (además de etiquetarla y asignarle responsable), podéis  (y debéis) hacer referencia a en qué _commit_ se soluciona el problema señalado. Para ello, basta copiar el número de commit (así: f9655b8) y GitHub hace el resto.

**Comment by adrilpz** [comment]
Se soluciona el error en el commit:
https://github.com/adrilpz/vyv/commit/f9655b8ff927b29096f51b95c88cc6ce4b1b5e5b
