### ISSUE TITLE
Integración con Travis

### ISSUE THREAD

**Issue by lauramcastro** [adrilpz/vyv#2]
El _badge_ que tenéis no se corresponde con la generación de este proyecto, sino con el que os puse de ejemplo (https://travis-ci.org/lauramcastro/java-travisCI-test). Recordad que, aunque ya la hayamos dejado atrás, este requisito de la primera semana es de obligado cumplimiento.

**Comment by adrilpz** [comment]
Se soluciona el error en el commit: https://github.com/adrilpz/vyv/commit/3ab639574d4f6e3e7d7f683c76c5470bbad45c7e
