### ISSUE TITLE
Atributos con visibilidad de paquete en ficheros de pruebas

### ISSUE THREAD

**Issue by lauramcastro** [adrilpz/vyv#9]
El fichero `ApuestasServiceTest.java`, por ejemplo, contiene una declaración _bulk_ de lo que está documentado como "variables globales", que en la práctica son un montón de atributos que, a falta de una visibilidad explícita, se convierten en atributos visibles a nivel de paquete. Restringid la visibilidad de dichos atributos para que sean privados, no hay razón para otra visibilidad diferente.

**Comment by adrilpz** [comment]
Problema resuelto en commit: https://github.com/adrilpz/vyv/commit/7a33c25be1e4118926883b599bd6cd805a21fee8
